# Global variables
supported_pids = []
supported_mids = []

# Dictionaries to store responses
pid_responses = {
    'PIDS_A': None,
    'PIDS_B': None,
    'PIDS_C': None,
}

mid_responses = {
    'MIDS_A': None,
    'MIDS_B': None,
    'MIDS_C': None,
    'MIDS_D': None,
    'MIDS_E': None,
    'MIDS_F': None
}

# DataFrame to store PID data
df = None

# Dictionary mapping PID numbers to their descriptions
pid_descriptions = {
    "00": "PIDS_A",
    "01": "STATUS",
    "02": "FREEZE_DTC",
    "03": "FUEL_STATUS",
    "04": "ENGINE_LOAD",
    "05": "COOLANT_TEMP",
    "06": "SHORT_FUEL_TRIM_1",
    "07": "LONG_FUEL_TRIM_1",
    "08": "SHORT_FUEL_TRIM_2",
    "09": "LONG_FUEL_TRIM_2",
    "0A": "FUEL_PRESSURE",
    "0B": "INTAKE_PRESSURE",
    "0C": "RPM",
    "0D": "SPEED",
    "0E": "TIMING_ADVANCE",
    "0F": "INTAKE_TEMP",
    "10": "MAF",
    "11": "THROTTLE_POS",
    "12": "AIR_STATUS",
    "13": "O2_SENSORS",
    "14": "O2_B1S1",
    "15": "O2_B1S2",
    "16": "O2_B1S3",
    "17": "O2_B1S4",
    "18": "O2_B2S1",
    "19": "O2_B2S2",
    "1A": "O2_B2S3",
    "1B": "O2_B2S4",
    "1C": "OBD_COMPLIANCE",
    "1D": "O2_SENSORS_ALT",
    "1E": "AUX_INPUT_STATUS",
    "1F": "RUN_TIME",
    "20": "PIDS_B",
    "21": "DISTANCE_W_MIL",
    "22": "FUEL_RAIL_PRESSURE_VAC",
    "23": "FUEL_RAIL_PRESSURE_DIRECT",
    "24": "O2_S1_WR_VOLTAGE",
    "25": "O2_S2_WR_VOLTAGE",
    "26": "O2_S3_WR_VOLTAGE",
    "27": "O2_S4_WR_VOLTAGE",
    "28": "O2_S5_WR_VOLTAGE",
    "29": "O2_S6_WR_VOLTAGE",
    "2A": "O2_S7_WR_VOLTAGE",
    "2B": "O2_S8_WR_VOLTAGE",
    "2C": "COMMANDED_EGR",
    "2D": "EGR_ERROR",
    "2E": "EVAPORATIVE_PURGE",
    "2F": "FUEL_LEVEL",
    "30": "WARMUPS_SINCE_DTC_CLEAR",
    "31": "DISTANCE_SINCE_DTC_CLEAR",
    "32": "EVAP_VAPOR_PRESSURE",
    "33": "BAROMETRIC_PRESSURE",
    "34": "O2_S1_WR_CURRENT",
    "35": "O2_S2_WR_CURRENT",
    "36": "O2_S3_WR_CURRENT",
    "37": "O2_S4_WR_CURRENT",
    "38": "O2_S5_WR_CURRENT",
    "39": "O2_S6_WR_CURRENT",
    "3A": "O2_S7_WR_CURRENT",
    "3B": "O2_S8_WR_CURRENT",
    "3C": "CATALYST_TEMP_B1S1",
    "3D": "CATALYST_TEMP_B2S1",
    "3E": "CATALYST_TEMP_B1S2",
    "3F": "CATALYST_TEMP_B2S2",
    "40": "PIDS_C",
    "41": "STATUS_DRIVE_CYCLE",
    "42": "CONTROL_MODULE_VOLTAGE",
    "43": "ABSOLUTE_LOAD",
    "44": "COMMANDED_EQUIV_RATIO",
    "45": "RELATIVE_THROTTLE_POS",
    "46": "AMBIANT_AIR_TEMP",
    "47": "THROTTLE_POS_B",
    "48": "THROTTLE_POS_C",
    "49": "ACCELERATOR_POS_D",
    "4A": "ACCELERATOR_POS_E",
    "4B": "ACCELERATOR_POS_F",
    "4C": "THROTTLE_ACTUATOR",
    "4D": "RUN_TIME_MIL",
    "4E": "TIME_SINCE_DTC_CLEARED",
    "4F": "unsupported",
    "50": "MAX_MAF",
    "51": "FUEL_TYPE",
    "52": "ETHANOL_PERCENT",
    "53": "EVAP_VAPOR_PRESSURE_ABS",
    "54": "EVAP_VAPOR_PRESSURE_ALT",
    "55": "SHORT_O2_TRIM_B1",
    "56": "LONG_O2_TRIM_B1",
    "57": "SHORT_O2_TRIM_B2",
    "58": "LONG_O2_TRIM_B2",
    "59": "FUEL_RAIL_PRESSURE_ABS",
    "5A": "RELATIVE_ACCEL_POS",
    "5B": "HYBRID_BATTERY_REMAINING",
    "5C": "OIL_TEMP",
    "5D": "FUEL_INJECT_TIMING",
    "5E": "FUEL_RATE",
    "5F": "unsupported"
}
mid_descriptions={
    '00' : 'MIDS_A',
    '01' :	'MONITOR_O2_B1S1',
    '02' :	'MONITOR_O2_B1S2',
    '03' :	'MONITOR_O2_B1S3',
    '04' :	'MONITOR_O2_B1S4',
    '05' :	'MONITOR_O2_B2S1',
    '06' :	'MONITOR_O2_B2S2',
    '07' :	'MONITOR_O2_B2S3',
    '08' :	'MONITOR_O2_B2S4',
    '09' :	'MONITOR_O2_B3S1',
    '0A' :	'MONITOR_O2_B3S2',
    '0B' :	'MONITOR_O2_B3S3',
    '0C' :	'MONITOR_O2_B3S4',
    '0D' :	'MONITOR_O2_B4S1',
    '0E' :	'MONITOR_O2_B4S2',
    '0F' :	'MONITOR_O2_B4S3',
    '10' :	'MONITOR_O2_B4S4',
    '20' :	'MIDS_B',
    '21' :	'MONITOR_CATALYST_B1',
    '22' :	'MONITOR_CATALYST_B2',
    '23' :	'MONITOR_CATALYST_B3',
    '24' :	'MONITOR_CATALYST_B4',
    '31' :	'MONITOR_EGR_B1',
    '32' :	'MONITOR_EGR_B2',
    '33' :	'MONITOR_EGR_B3',
    '34' : 	'MONITOR_EGR_B4',
    '35' : 	'MONITOR_VVT_B1',
    '36' : 	'MONITOR_VVT_B2',
    '37' : 	'MONITOR_VVT_B3',
    '38' : 	'MONITOR_VVT_B4',
    '39' : 	'MONITOR_EVAP_150',
    '3A' : 	'MONITOR_EVAP_090',
    '3B' : 	'MONITOR_EVAP_040',
    '3C' : 	'MONITOR_EVAP_020',
    '3D' : 	'MONITOR_PURGE_FLOW',
    '40' : 	'MIDS_C',
    '41' : 	'MONITOR_O2_HEATER_B1S1',
    '42' :  'MONITOR_O2_HEATER_B1S2',
    '43' : 	'MONITOR_O2_HEATER_B1S3',
    '44' : 	'MONITOR_O2_HEATER_B1S4',
    '45' : 	'MONITOR_O2_HEATER_B2S1',
    '46' : 	'MONITOR_O2_HEATER_B2S2',
    '47' : 	'MONITOR_O2_HEATER_B2S3',
    '48' : 	'MONITOR_O2_HEATER_B2S4',
    '49' :	'MONITOR_O2_HEATER_B3S1',
    '4A' :	'MONITOR_O2_HEATER_B3S2',
    '4B' :	'MONITOR_O2_HEATER_B3S3',
    '4C' :	'MONITOR_O2_HEATER_B3S4',
    '4D' :	'MONITOR_O2_HEATER_B4S1',
    '4E' :	'MONITOR_O2_HEATER_B4S2',
    '4F' :	'MONITOR_O2_HEATER_B4S3',
    '50' :	'MONITOR_O2_HEATER_B4S4',
    '60' :	'MIDS_D',
    '61' :	'MONITOR_HEATED_CATALYST_B1',
    '62' :	'MONITOR_HEATED_CATALYST_B2',
    '63' :	'MONITOR_HEATED_CATALYST_B3',
    '64' :	'MONITOR_HEATED_CATALYST_B4',
    '71' :	'MONITOR_SECONDARY_AIR_1',
    '72' :	'MONITOR_SECONDARY_AIR_2',
    '73' :	'MONITOR_SECONDARY_AIR_3',
    '74' :	'MONITOR_SECONDARY_AIR_4',
    '80' :	'MIDS_E',
    '81' :	'MONITOR_FUEL_SYSTEM_B1',
    '82' :	'MONITOR_FUEL_SYSTEM_B2',
    '83' :	'MONITOR_FUEL_SYSTEM_B3',
    '84' :	'MONITOR_FUEL_SYSTEM_B4',
    '85' :	'MONITOR_BOOST_PRESSURE_B1',
    '86' :	'MONITOR_BOOST_PRESSURE_B2',
    '90' :	'MONITOR_NOX_ABSORBER_B1',
    '91' :	'MONITOR_NOX_ABSORBER_B2',
    '98' :	'MONITOR_NOX_CATALYST_B1',
    '99' :	'MONITOR_NOX_CATALYST_B2',
    'A0' :	'MIDS_F',
    'A1' :	'MONITOR_MISFIRE_GENERAL',
    'A2' :	'MONITOR_MISFIRE_CYLINDER_1',
    'A3' :	'MONITOR_MISFIRE_CYLINDER_2',
    'A4' :	'MONITOR_MISFIRE_CYLINDER_3',
    'A5' :	'MONITOR_MISFIRE_CYLINDER_4',
    'A6' :	'MONITOR_MISFIRE_CYLINDER_5',
    'A7' :	'MONITOR_MISFIRE_CYLINDER_6',
    'A8' :	'MONITOR_MISFIRE_CYLINDER_7',
    'A9' :	'MONITOR_MISFIRE_CYLINDER_8',
    'AA' : 	'MONITOR_MISFIRE_CYLINDER_9',
    'AB' : 	'MONITOR_MISFIRE_CYLINDER_10',
    'AC' : 	'MONITOR_MISFIRE_CYLINDER_11',
    'AD' : 	'MONITOR_MISFIRE_CYLINDER_12',
    'B0' : 	'MONITOR_PM_FILTER_B1',
    'B1' : 	'MONITOR_PM_FILTER_B2'
}